In [16]:
import pandas as pd

# 1. Load the dataset

In [17]:
df = pd.read_csv("student_performance_finalscore.csv")

# 2. Understanding the dataset

In [ ]:
df.head() # first 5 cols

,Student_ID,Age,Gender,Hours_Studied,Attendance,Sleep_Hours,Stress_Level,Screen_Time,Previous_GPA,Part_Time_Job,Study_Method,Diet_Quality,Internet_Quality,Extracurricular,Tutoring_Sessions_Per_Week,Family_Income_Level,Exam_Anxiety_Score,Final_Score
0,STU00001,17,Female,8.20,80.0,7.3,2.3,3.2,3.07,No,Online,Average,Average,Yes,3,High,1.8,87.10
1,STU00002,22,Male,4.07,69.2,7.9,3.6,0.5,2.66,Yes,Offline,Average,Good,No,2,Middle,1.0,92.03
2,STU00003,23,Female,5.07,74.2,6.7,2.6,4.7,3.27,No,Hybrid,Average,Good,No,1,Middle,4.2,95.37
3,STU00004,22,Female,5.82,82.5,3.7,3.3,2.3,2.87,No,Offline,Average,Excellent,No,0,Middle,3.6,90.73
4,STU00005,21,Male,3.42,90.8,7.4,7.0,3.1,2.82,Yes,Offline,Average,Good,No,2,Middle,4.5,74.71

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 18 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Student_ID                  8000 non-null   str
 1   Age                         8000 non-null   int64
 2   Gender                      8000 non-null   str
 3   Hours_Studied               8000 non-null   float64
 4   Attendance                  8000 non-null   float64
 5   Sleep_Hours                 8000 non-null   float64
 6   Stress_Level                8000 non-null   float64
 7   Screen_Time                 8000 non-null   float64
 8   Previous_GPA                8000 non-null   float64
 9   Part_Time_Job               8000 non-null   str
 10  Study_Method                8000 non-null   str
 11  Diet_Quality                8000 non-null   str
 12  Internet_Quality            8000 non-null   str
 13  Extracurricular             8000 non-null   str
 14  Tutoring_Sessions_Per_Week  8000 non-null   int64
 15  Family_Income_Level         8000 non-null   str
 16  Exam_Anxiety_Score          8000 non-null   float64
 17  Final_Score                 8000 non-null   float64
dtypes: float64(8), int64(2), str(8)
memory usage: 1.1 MB

In [8]:
df.describe()

,Age,Hours_Studied,Attendance,Sleep_Hours,Stress_Level,Screen_Time,Previous_GPA,Tutoring_Sessions_Per_Week,Exam_Anxiety_Score,Final_Score
count,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000
mean,20.494375,4.983845,79.933375,6.989125,5.014175,4.024525,2.992408,1.700625,4.494238,83.205649
std,2.285962,1.951715,9.656594,1.192898,1.940126,1.481908,0.489530,1.112836,1.685571,12.756728
min,17.000000,0.020000,43.300000,3.000000,1.000000,0.500000,1.500000,0.000000,1.000000,22.810000
25%,18.000000,3.680000,73.400000,6.200000,3.700000,3.000000,2.670000,1.000000,3.300000,75.507500
50%,20.500000,4.980000,80.100000,7.000000,5.000000,4.000000,2.990000,2.000000,4.400000,86.510000
75%,22.000000,6.312500,86.600000,7.800000,6.300000,5.000000,3.330000,2.000000,5.600000,93.080000
max,24.000000,12.000000,100.000000,10.000000,10.000000,9.600000,6.700000,5.000000,10.000000,99.980000

In [9]:
df.columns

Index(['Student_ID', 'Age', 'Gender', 'Hours_Studied', 'Attendance',
       'Sleep_Hours', 'Stress_Level', 'Screen_Time', 'Previous_GPA',
       'Part_Time_Job', 'Study_Method', 'Diet_Quality', 'Internet_Quality',
       'Extracurricular', 'Tutoring_Sessions_Per_Week', 'Family_Income_Level',
       'Exam_Anxiety_Score', 'Final_Score'],
      dtype='str')

In [12]:
df.isnull().sum()

Student_ID                    0
Age                           0
Gender                        0
Hours_Studied                 0
Attendance                    0
Sleep_Hours                   0
Stress_Level                  0
Screen_Time                   0
Previous_GPA                  0
Part_Time_Job                 0
Study_Method                  0
Diet_Quality                  0
Internet_Quality              0
Extracurricular               0
Tutoring_Sessions_Per_Week    0
Family_Income_Level           0
Exam_Anxiety_Score            0
Final_Score                   0
dtype: int64

In [11]:
df.duplicated().sum()

np.int64(0)

In [13]:
df.dtypes

Student_ID                        str
Age                             int64
Gender                            str
Hours_Studied                 float64
Attendance                    float64
Sleep_Hours                   float64
Stress_Level                  float64
Screen_Time                   float64
Previous_GPA                  float64
Part_Time_Job                     str
Study_Method                      str
Diet_Quality                      str
Internet_Quality                  str
Extracurricular                   str
Tutoring_Sessions_Per_Week      int64
Family_Income_Level               str
Exam_Anxiety_Score            float64
Final_Score                   float64
dtype: object

# 3. Execute the numerical columns

In [21]:
numerical_df = df.select_dtypes(include=["int64", "float64"])
numerical_df.columns

Index(['Age', 'Hours_Studied', 'Attendance', 'Sleep_Hours', 'Stress_Level',
       'Screen_Time', 'Previous_GPA', 'Tutoring_Sessions_Per_Week',
       'Exam_Anxiety_Score', 'Final_Score'],
      dtype='str')

# 4. Execute the Categorical columns

In [26]:
categorical_df = df.select_dtypes(include=["object", "string"])
categorical_df.columns

Index(['Student_ID', 'Gender', 'Part_Time_Job', 'Study_Method', 'Diet_Quality',
       'Internet_Quality', 'Extracurricular', 'Family_Income_Level'],
      dtype='str')

##  - Analysis

In [27]:
numerical_df.describe()

,Age,Hours_Studied,Attendance,Sleep_Hours,Stress_Level,Screen_Time,Previous_GPA,Tutoring_Sessions_Per_Week,Exam_Anxiety_Score,Final_Score
count,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000
mean,20.494375,4.983845,79.933375,6.989125,5.014175,4.024525,2.992408,1.700625,4.494238,83.205649
std,2.285962,1.951715,9.656594,1.192898,1.940126,1.481908,0.489530,1.112836,1.685571,12.756728
min,17.000000,0.020000,43.300000,3.000000,1.000000,0.500000,1.500000,0.000000,1.000000,22.810000
25%,18.000000,3.680000,73.400000,6.200000,3.700000,3.000000,2.670000,1.000000,3.300000,75.507500
50%,20.500000,4.980000,80.100000,7.000000,5.000000,4.000000,2.990000,2.000000,4.400000,86.510000
75%,22.000000,6.312500,86.600000,7.800000,6.300000,5.000000,3.330000,2.000000,5.600000,93.080000
max,24.000000,12.000000,100.000000,10.000000,10.000000,9.600000,6.700000,5.000000,10.000000,99.980000

In [28]:
categorical_df.describe()

,Student_ID,Gender,Part_Time_Job,Study_Method,Diet_Quality,Internet_Quality,Extracurricular,Family_Income_Level
count,8000,8000,8000,8000,8000,8000,8000,8000
unique,8000,3,2,3,3,4,2,3
top,STU00001,Male,No,Offline,Average,Good,No,Middle
freq,1,3906,4803,3170,3980,3266,4381,3912

In [ ]:
corr_matrix = numerical_df.corr()
corr_matrix

,Age,Hours_Studied,Attendance,Sleep_Hours,Stress_Level,Screen_Time,Previous_GPA,Tutoring_Sessions_Per_Week,Exam_Anxiety_Score,Final_Score
Age,1.000000,-0.000788,-0.000055,-0.005313,-0.011280,0.002727,0.013405,0.005456,-0.010126,0.017103
Hours_Studied,-0.000788,1.000000,0.017252,0.019577,-0.010874,0.000189,0.012320,0.266811,-0.286131,0.591355
Attendance,-0.000055,0.017252,1.000000,0.003726,-0.007547,0.003384,0.010618,0.060990,-0.090481,0.168615
Sleep_Hours,-0.005313,0.019577,0.003726,1.000000,0.031963,-0.011176,0.004398,0.072491,-0.085347,0.151673
Stress_Level,-0.011280,-0.010874,-0.007547,0.031963,1.000000,0.000577,-0.001236,-0.169636,0.158435,-0.296634
Screen_Time,0.002727,0.000189,0.003384,-0.011176,0.000577,1.000000,0.008390,-0.050811,0.069986,-0.135252
Previous_GPA,0.013405,0.012320,0.010618,0.004398,-0.001236,0.008390,1.000000,0.138943,-0.156278,0.291002
Tutoring_Sessions_Per_Week,0.005456,0.266811,0.060990,0.072491,-0.169636,-0.050811,0.138943,1.000000,-0.235214,0.471524
Exam_Anxiety_Score,-0.010126,-0.286131,-0.090481,-0.085347,0.158435,0.069986,-0.156278,-0.235214,1.000000,-0.494940
Final_Score,0.017103,0.591355,0.168615,0.151673,-0.296634,-0.135252,0.291002,0.471524,-0.494940,1.000000

In [31]:
corr_matrix["Final_Score"].sort_values(ascending=False)

Final_Score                   1.000000
Hours_Studied                 0.591355
Tutoring_Sessions_Per_Week    0.471524
Previous_GPA                  0.291002
Attendance                    0.168615
Sleep_Hours                   0.151673
Age                           0.017103
Screen_Time                  -0.135252
Stress_Level                 -0.296634
Exam_Anxiety_Score           -0.494940
Name: Final_Score, dtype: float64

In [34]:
for col in categorical_df.columns:
    print("\n", col)
    print(categorical_df[col].value_counts())

 Student_ID
Student_ID
STU00001    1
STU00002    1
STU00003    1
STU00004    1
STU00005    1
           ..
STU07996    1
STU07997    1
STU07998    1
STU07999    1
STU08000    1
Name: count, Length: 8000, dtype: int64

 Gender
Gender
Male          3906
Female        3810
Non-Binary     284
Name: count, dtype: int64

 Part_Time_Job
Part_Time_Job
No     4803
Yes    3197
Name: count, dtype: int64

 Study_Method
Study_Method
Offline    3170
Online     2460
Hybrid     2370
Name: count, dtype: int64

 Diet_Quality
Diet_Quality
Average    3980
Poor       2026
Good       1994
Name: count, dtype: int64

 Internet_Quality
Internet_Quality
Good         3266
Average      2285
Excellent    1629
Poor          820
Name: count, dtype: int64

 Extracurricular
Extracurricular
No     4381
Yes    3619
Name: count, dtype: int64

 Family_Income_Level
Family_Income_Level
Middle    3912
Low       2048
High      2040
Name: count, dtype: int64